/**
 * Seed data fallback for when the SQLite database is unavailable
 * (e.g. on Vercel serverless functions with no persistent filesystem).
 *
 * These types mirror the Prisma-generated shapes but use plain TypeScript
 * interfaces so no Prisma imports are needed.
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SeedCategory {
  id: string
  name: string
  nameSi?: string
  nameTa?: string
  icon: string
  slug: string
  bookCount: number
}

export interface SeedCategoryEmbedded {
  id: string
  name: string
  nameSi?: string
  nameTa?: string
  icon: string
  slug: string
  bookCount: number
}

export interface SeedBook {
  id: string
  title: string
  titleSi?: string
  titleTa?: string
  author: string
  publisher?: string
  isbn?: string
  language: string
  year?: number
  pageCount?: number
  description?: string
  coverImage?: string
  categoryId?: string
  status: string
  addedById: string
  likes: number
  readingCount: number
  listeningCount: number
  createdAt: string
  updatedAt: string
  category?: SeedCategoryEmbedded | null
  commentCount?: number
  inBookshelf?: boolean
}

// ─── Categories ──────────────────────────────────────────────────────────────

export const SEED_CATEGORIES: SeedCategory[] = [
  { id: 'cat-fiction', name: 'Fiction & Novels', nameSi: 'ප්‍රබන්ධ සහ නවකතා', nameTa: 'புனைவு மற்றும் நாவல்கள்', icon: '📖', slug: 'fiction', bookCount: 2 },
  { id: 'cat-children', name: "Children's Books", nameSi: 'ළමා පොත්', nameTa: 'குழந்தைகள் புத்தகங்கள்', icon: '🧸', slug: 'children', bookCount: 2 },
  { id: 'cat-biography', name: 'Biography', nameSi: 'චරිතාපදාන', nameTa: 'சுயசரிதை', icon: '👤', slug: 'biography', bookCount: 2 },
  { id: 'cat-history', name: 'History', nameSi: 'ඉතිහාසය', nameTa: 'வரலாறு', icon: '🏛️', slug: 'history', bookCount: 1 },
  { id: 'cat-self-help', name: 'Self-Help', nameSi: 'ස්වයං සහාය', nameTa: 'சுய உதவி', icon: '🧘', slug: 'self-help', bookCount: 1 },
  { id: 'cat-poetry', name: 'Poetry', nameSi: 'කවි', nameTa: 'கவிதை', icon: '🌸', slug: 'poetry', bookCount: 1 },
  { id: 'cat-science', name: 'Science', nameSi: 'විද්‍යාව', nameTa: 'அறிவியல்', icon: '🔬', slug: 'science', bookCount: 1 },
  { id: 'cat-ayurveda', name: 'Ayurveda', nameSi: 'ආයුර්වේදය', nameTa: 'ஆயுர்வேதம்', icon: '🌿', slug: 'ayurveda', bookCount: 1 },
  { id: 'cat-astrology', name: 'Astrology', nameSi: 'ජ්‍යෝතිෂය', nameTa: 'ஜோதிடம்', icon: '🔮', slug: 'astrology', bookCount: 1 },
  { id: 'cat-adventure', name: 'Adventure', nameSi: 'විස්සායන', nameTa: 'சாகசம்', icon: '🗺️', slug: 'adventure', bookCount: 2 },
  { id: 'cat-romance', name: 'Romance', nameSi: 'ප්‍රේම වෘත්තී', nameTa: 'காதல் கதைகள்', icon: '💕', slug: 'romance', bookCount: 1 },
  { id: 'cat-cooking', name: 'Cooking', nameSi: 'කෑම සෑදීම', nameTa: 'சம෈யல்', icon: '🍳', slug: 'cooking', bookCount: 1 },
  { id: 'cat-dictionaries', name: 'Dictionaries', nameSi: 'ශබ්දකෝෂ', nameTa: 'அகராதிகள்', icon: '📚', slug: 'dictionaries', bookCount: 1 },
  { id: 'cat-teens', name: 'Teens', nameSi: 'යොවුන්', nameTa: 'இளம் வயதினர்', icon: '🎯', slug: 'teens', bookCount: 1 },
  { id: 'cat-religion', name: 'Religion', nameSi: 'ආගම', nameTa: 'மதம்', icon: '🙏', slug: 'religion', bookCount: 1 },
  { id: 'cat-business', name: 'Business', nameSi: 'ව්‍යාපාර', nameTa: 'வணிகம்', icon: '💼', slug: 'business', bookCount: 1 },
]

// ─── Helper: look up a category by slug ──────────────────────────────────────

const catBySlug = (slug: string): SeedCategoryEmbedded | undefined =>
  SEED_CATEGORIES.find((c) => c.slug === slug)

// ─── Books ───────────────────────────────────────────────────────────────────

export const SEED_BOOKS: SeedBook[] = [
  {
    id: 'seed-book-01',
    title: 'සරයන් අත්හගේ කතා',
    author: 'ප්‍රේමදාස ශ්‍රී අලවත්තගේ',
    publisher: 'S. Godage & Brothers',
    language: 'sinhala',
    year: 1985,
    pageCount: 120,
    description: "A beloved Sinhala children's story about a young boy named Sarayan and his adventures with a gentle elephant in a rural Sri Lankan village. Filled with warmth, humor, and valuable life lessons.",
    coverImage: '/covers/book1.png',
    categoryId: 'cat-children',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 234,
    readingCount: 1200,
    listeningCount: 89,
    createdAt: '2024-01-15T10:00:00.000Z',
    updatedAt: '2024-01-15T10:00:00.000Z',
    category: catBySlug('children'),
  },
  {
    id: 'seed-book-02',
    title: 'The Tea Garden Mystery',
    author: 'Michael Ondaatje',
    publisher: 'Perera-Hussein',
    language: 'english',
    year: 2019,
    pageCount: 342,
    description: 'A captivating literary fiction novel set in the misty tea plantations of Nuwara Eliya. When a young planter disappears, the secrets buried in the emerald hills begin to surface.',
    coverImage: '/covers/book2.png',
    categoryId: 'cat-fiction',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 567,
    readingCount: 3400,
    listeningCount: 234,
    createdAt: '2024-02-10T10:00:00.000Z',
    updatedAt: '2024-02-10T10:00:00.000Z',
    category: catBySlug('fiction'),
  },
  {
    id: 'seed-book-03',
    title: 'මල් සුවඳ කවි',
    author: 'මහාගම සේකේර',
    publisher: 'M.D. Gunasena',
    language: 'sinhala',
    year: 1998,
    pageCount: 88,
    description: 'A collection of exquisite Sinhala poetry exploring themes of love, nature, and spirituality. Each verse is a fragrant bloom in the garden of Sri Lankan literature.',
    coverImage: '/covers/book3.png',
    categoryId: 'cat-poetry',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 189,
    readingCount: 890,
    listeningCount: 56,
    createdAt: '2024-03-05T10:00:00.000Z',
    updatedAt: '2024-03-05T10:00:00.000Z',
    category: catBySlug('poetry'),
  },
  {
    id: 'seed-book-04',
    title: 'Ancient Ceylon: Rise of Kingdoms',
    author: 'Prof. Senarath Paranavithana',
    publisher: 'Lake House',
    language: 'english',
    year: 2005,
    pageCount: 456,
    description: "A comprehensive exploration of Sri Lanka's ancient civilizations, from the founding of Anuradhapura to the glory of Polonnaruwa. Richly illustrated with photographs and archaeological findings.",
    coverImage: '/covers/book4.png',
    categoryId: 'cat-history',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 445,
    readingCount: 2100,
    listeningCount: 123,
    createdAt: '2024-03-20T10:00:00.000Z',
    updatedAt: '2024-03-20T10:00:00.000Z',
    category: catBySlug('history'),
  },
  {
    id: 'seed-book-05',
    title: "English-Sinhala Children's Dictionary",
    author: 'Educational Publications Dept',
    publisher: 'EAP Publications',
    language: 'english',
    year: 2020,
    pageCount: 200,
    description: 'A beautifully illustrated bilingual dictionary designed for young learners. Features over 2,000 words with colorful pictures, making learning both English and Sinhala fun and engaging.',
    coverImage: '/covers/book5.png',
    categoryId: 'cat-dictionaries',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 321,
    readingCount: 4500,
    listeningCount: 78,
    createdAt: '2024-04-01T10:00:00.000Z',
    updatedAt: '2024-04-01T10:00:00.000Z',
    category: catBySlug('dictionaries'),
  },
  {
    id: 'seed-book-06',
    title: 'හෙර්බල් වෙදකම',
    author: 'Dr. A. H. M. J. Pushpakumara',
    publisher: 'Sarasavi',
    language: 'sinhala',
    year: 2015,
    pageCount: 320,
    description: 'A comprehensive guide to traditional Sri Lankan Ayurvedic medicine, featuring detailed descriptions of medicinal plants, their properties, preparation methods, and traditional remedies passed down through generations.',
    coverImage: '/covers/book6.png',
    categoryId: 'cat-ayurveda',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 278,
    readingCount: 1560,
    listeningCount: 45,
    createdAt: '2024-04-15T10:00:00.000Z',
    updatedAt: '2024-04-15T10:00:00.000Z',
    category: catBySlug('ayurveda'),
  },
  {
    id: 'seed-book-07',
    title: 'Bandaranaike: The Man and His Vision',
    author: 'K. M. de Silva',
    publisher: 'Vijitha Yapa',
    language: 'english',
    year: 2012,
    pageCount: 528,
    description: "The definitive biography of S.W.R.D. Bandaranaike, one of Sri Lanka's most influential political leaders. This meticulously researched work reveals the man behind the legend and his lasting impact on the nation.",
    coverImage: '/covers/book7.png',
    categoryId: 'cat-biography',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 398,
    readingCount: 1890,
    listeningCount: 67,
    createdAt: '2024-05-01T10:00:00.000Z',
    updatedAt: '2024-05-01T10:00:00.000Z',
    category: catBySlug('biography'),
  },
  {
    id: 'seed-book-08',
    title: "Leopard's Trail",
    author: 'Karen Connelly',
    publisher: 'Godage International',
    language: 'english',
    year: 2021,
    pageCount: 298,
    description: "An thrilling adventure novel set in the untamed jungles of Yala National Park. When a young wildlife researcher encounters a mysterious leopard, she uncovers an ancient secret that could change everything.",
    coverImage: '/covers/book8.png',
    categoryId: 'cat-adventure',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 612,
    readingCount: 2780,
    listeningCount: 189,
    createdAt: '2024-05-15T10:00:00.000Z',
    updatedAt: '2024-05-15T10:00:00.000Z',
    category: catBySlug('adventure'),
  },
  {
    id: 'seed-book-09',
    title: 'ජ්‍යෝතිෂ දර්ශනය',
    author: 'ජ්‍යෝතිෂී සුමංගල',
    publisher: 'Ravaya Publications',
    language: 'sinhala',
    year: 2010,
    pageCount: 400,
    description: 'A comprehensive guide to Sinhala astrology covering zodiac signs, planetary positions, birth chart interpretations, and predictions. An essential reference for anyone interested in traditional Sri Lankan astrology.',
    coverImage: '/covers/book9.png',
    categoryId: 'cat-astrology',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 456,
    readingCount: 3200,
    listeningCount: 234,
    createdAt: '2024-06-01T10:00:00.000Z',
    updatedAt: '2024-06-01T10:00:00.000Z',
    category: catBySlug('astrology'),
  },
  {
    id: 'seed-book-10',
    title: 'Sunset at Hikkaduwa',
    author: 'Ameena Hussein',
    publisher: 'Perera-Hussein',
    language: 'english',
    year: 2022,
    pageCount: 220,
    description: 'A heartwarming coming-of-age story set in the coastal town of Hikkaduwa. Two teenagers from different backgrounds find friendship and first love during one unforgettable summer.',
    coverImage: '/covers/book10.png',
    categoryId: 'cat-teens',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 289,
    readingCount: 1340,
    listeningCount: 98,
    createdAt: '2024-06-15T10:00:00.000Z',
    updatedAt: '2024-06-15T10:00:00.000Z',
    category: catBySlug('teens'),
  },
  {
    id: 'seed-book-11',
    title: 'The Summit Within',
    author: 'Daisaku Ikeda',
    publisher: 'S. Godage & Brothers',
    language: 'english',
    year: 2018,
    pageCount: 276,
    description: "An inspirational guide to personal transformation and inner peace. Drawing from Buddhist philosophy and modern psychology, this book offers practical wisdom for overcoming life's challenges.",
    coverImage: '/covers/book11.png',
    categoryId: 'cat-self-help',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 534,
    readingCount: 4100,
    listeningCount: 156,
    createdAt: '2024-07-01T10:00:00.000Z',
    updatedAt: '2024-07-01T10:00:00.000Z',
    category: catBySlug('self-help'),
  },
  {
    id: 'seed-book-12',
    title: 'Sri Lankan Kitchen: 100 Recipes',
    author: 'Chandra Dissanayake',
    publisher: 'Stamford Lake',
    language: 'english',
    year: 2019,
    pageCount: 248,
    description: 'A beautifully photographed cookbook featuring 100 authentic Sri Lankan recipes. From aromatic rice dishes to spicy curries, sweet hoppers to fresh sambols — discover the rich flavors of Sri Lankan cuisine.',
    coverImage: '/covers/book12.png',
    categoryId: 'cat-cooking',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 423,
    readingCount: 2800,
    listeningCount: 34,
    createdAt: '2024-07-15T10:00:00.000Z',
    updatedAt: '2024-07-15T10:00:00.000Z',
    category: catBySlug('cooking'),
  },
  {
    id: 'seed-book-13',
    title: 'රන් සිරිපා',
    author: 'මාර්ටින් වික්‍රමසිංහ',
    publisher: 'S. Godage & Brothers',
    language: 'sinhala',
    year: 1975,
    pageCount: 380,
    description: 'A masterpiece of Sinhala literature exploring social themes through the life of a village goldsmith. Rich in cultural detail and human emotion.',
    coverImage: '/covers/book2.png',
    categoryId: 'cat-fiction',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 789,
    readingCount: 5600,
    listeningCount: 345,
    createdAt: '2024-08-01T10:00:00.000Z',
    updatedAt: '2024-08-01T10:00:00.000Z',
    category: catBySlug('fiction'),
  },
  {
    id: 'seed-book-14',
    title: "The Ocean's Embrace",
    author: 'Michelle de Kretser',
    publisher: 'Perera-Hussein',
    language: 'english',
    year: 2020,
    pageCount: 304,
    description: 'A sweeping romance that moves between Colombo and Melbourne. Two lovers separated by distance and time find that the ocean between them is both barrier and bridge.',
    coverImage: '/covers/book10.png',
    categoryId: 'cat-romance',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 345,
    readingCount: 1560,
    listeningCount: 78,
    createdAt: '2024-08-15T10:00:00.000Z',
    updatedAt: '2024-08-15T10:00:00.000Z',
    category: catBySlug('romance'),
  },
  {
    id: 'seed-book-15',
    title: 'Young Explorers: Wildlife of Sri Lanka',
    author: 'Jehan CanagaRetna',
    publisher: 'Jetwing',
    language: 'english',
    year: 2021,
    pageCount: 64,
    description: "An exciting introduction to Sri Lanka's incredible wildlife for young readers. Packed with fun facts, stunning photographs, and activities.",
    coverImage: '/covers/book8.png',
    categoryId: 'cat-children',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 267,
    readingCount: 1890,
    listeningCount: 123,
    createdAt: '2024-09-01T10:00:00.000Z',
    updatedAt: '2024-09-01T10:00:00.000Z',
    category: catBySlug('children'),
  },
  {
    id: 'seed-book-16',
    title: 'විද්‍යාව හා ජීවිතය',
    author: 'මහාචාර්ය ජයන්ත ජයවර්ධන',
    publisher: 'Sarasavi',
    language: 'sinhala',
    year: 2016,
    pageCount: 350,
    description: 'A fascinating exploration of how science impacts our daily lives. Written in accessible Sinhala for general readers curious about the world around them.',
    coverImage: '/covers/book4.png',
    categoryId: 'cat-science',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 198,
    readingCount: 980,
    listeningCount: 45,
    createdAt: '2024-09-15T10:00:00.000Z',
    updatedAt: '2024-09-15T10:00:00.000Z',
    category: catBySlug('science'),
  },
  {
    id: 'seed-book-17',
    title: 'Buddhist Philosophy for Modern Life',
    author: 'Ven. Dr. Walpola Rahula',
    publisher: 'BPS Publications',
    language: 'english',
    year: 2008,
    pageCount: 290,
    description: "A clear and accessible introduction to core Buddhist teachings and how they apply to contemporary challenges. By one of Sri Lanka's most respected scholars.",
    coverImage: '/covers/book3.png',
    categoryId: 'cat-religion',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 567,
    readingCount: 3450,
    listeningCount: 267,
    createdAt: '2024-10-01T10:00:00.000Z',
    updatedAt: '2024-10-01T10:00:00.000Z',
    category: catBySlug('religion'),
  },
  {
    id: 'seed-book-18',
    title: 'Startup Sri Lanka',
    author: 'Rohan Jayaweera',
    publisher: 'Vijitha Yapa',
    language: 'english',
    year: 2023,
    pageCount: 240,
    description: 'An inspiring guide for aspiring entrepreneurs in Sri Lanka. Featuring real stories of local startups, practical advice, and insights into building successful businesses.',
    coverImage: '/covers/book7.png',
    categoryId: 'cat-business',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 234,
    readingCount: 1230,
    listeningCount: 56,
    createdAt: '2024-10-15T10:00:00.000Z',
    updatedAt: '2024-10-15T10:00:00.000Z',
    category: catBySlug('business'),
  },
  {
    id: 'seed-book-19',
    title: 'මා සහ මගේ පොත්',
    author: 'අශෝක පෙරේරා',
    publisher: 'M.D. Gunasena',
    language: 'sinhala',
    year: 2017,
    pageCount: 180,
    description: 'A touching memoir by a beloved Sri Lankan author, reflecting on the books that shaped his life and the literary journey that defined his career.',
    coverImage: '/covers/book7.png',
    categoryId: 'cat-biography',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 156,
    readingCount: 670,
    listeningCount: 23,
    createdAt: '2024-11-01T10:00:00.000Z',
    updatedAt: '2024-11-01T10:00:00.000Z',
    category: catBySlug('biography'),
  },
  {
    id: 'seed-book-20',
    title: 'Island of Spells',
    author: 'Nihal de Silva',
    publisher: 'Godage International',
    language: 'english',
    year: 2014,
    pageCount: 356,
    description: 'A thrilling adventure that weaves through the ancient cities and magical landscapes of Sri Lanka. When a young archaeologist discovers an ancient manuscript, a dangerous quest begins.',
    coverImage: '/covers/book8.png',
    categoryId: 'cat-adventure',
    status: 'community',
    addedById: 'demo-user-001',
    likes: 478,
    readingCount: 2340,
    listeningCount: 178,
    createdAt: '2024-11-15T10:00:00.000Z',
    updatedAt: '2024-11-15T10:00:00.000Z',
    category: catBySlug('adventure'),
  },
]